# fly.toml app configuration file generated for tw-opendata-cultureinfo-w-slack on 2023-08-27T20:37:45+08:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tw-opendata-cultureinfo-w-slack"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "1400"

[http_service]
  internal_port = 1400
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
